paths:
  /dragoes:
    get:
      summary: Retorna a lista de todos os dragões cadastrados
      tags: [Dragoes]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de Dragões
          content:
            application/json:
              schema:
                type: object
                properties:
                  dragoes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Dragao'
        500:
          description: Erro interno do servidor

    post:
      summary: Cadastra um novo dragão
      tags: [Dragoes]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DragaoInput'
      responses:
        201:
          description: O dragão foi cadastrado com sucesso
        500:
          description: Erro interno do servidor

  /dragoes/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: ID única do dragão (MongoDB ObjectId)

    put:
      summary: Altera um dragão existente
      tags: [Dragoes]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DragaoInput'
      responses:
        200:
          description: Dragão atualizado com sucesso
        400:
          description: Erro na validação da ID
        500:
          description: Erro interno do servidor
    get:
      summary: Retorna os detalhes de um dragão específico
      tags: [Dragoes]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Detalhes do dragão encontrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dragao'
              example:
                _id: "69cd6a50b4e74e92a7ecaa00"
                name: "Viserion"
                description: "Ressuscitado como dragão de gelo pelo Rei da Noite."
                assembler: "Rei da Noite"
                inspiredName: "Viserys Targaryen"
                caracteristics:
                  size: "Grande"
                  color: "Creme/Dourado (Vivo) ou Azul (Morto)"
                  temperament: "Submisso"
                  specialAbility: "Sopro de fogo azul/gelo"
        400:
          description: Erro na validação da ID
        404:
          description: Dragão não encontrado
        500:
          description: Erro interno do servidor  

    delete:
      summary: Exclui um dragão do catálogo
      tags: [Dragoes]
      security:
        - bearerAuth: []
      responses:
        204:
          description: O dragão foi excluído com sucesso
        400:
          description: Erro na validação da ID
        500:
          description: Erro interno do servidor
  /users:
    post:
      summary: Cadastra um novo usuário
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersInput'
      responses:
        201:
          description: Usuário cadastrado com sucesso
        500:
          description: Erro interno do servidor

  /login:
    post:
      summary: Realiza o login do usuário
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersInput'
        200:
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        401:
          description: Credenciais inválidas
        404:
          description: Usuário não encontrado

components:
  schemas:
    Caracteristics:
      type: object
      properties:
        size:
          type: string
          example: "Grande"
        color:
          type: string
          example: "Verde e Bronze"
        temperament:
          type: string
          example: "Leal"
        specialAbility:
          type: string
          example: "Ataques aéreos rápidos"

    Dragao:
      type: object
      properties:
        _id:
          type: string
          example: "69cd6a46b4e74e92a7eca9fd"
        name:
          type: string
          example: "Rhaegal"
        description:
          type: string
          example: "Dragão ágil e bom em combate aéreo."
        assembler:
          type: string
          example: "Jon Snow"
        inspiredName:
          type: string
          example: "Rhaegar Targaryen"
        caracteristics:
          $ref: '#/components/schemas/Caracteristics'
      

    DragaoInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Drogon"
        description:
          type: string
          example: "O maior e mais agressivo dos três."
        assembler:
          type: string
          example: "Daenerys Targaryen"
        inspiredName:
          type: string
          example: "Drogo"
        caracteristics:
          $ref: '#/components/schemas/Caracteristics'

    UsersInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Geovanna"
        email:
          type: string
          example: "geovanna@gmail.com"
        senha:
          type: string
          example: "$3b@43$Kq8xkFWwaQR7spzS45VKCuQTTiK99sb15NuAJV3UJ"

    securitySchemes:
    bearerAuth:            # Este nome deve ser igual ao que você usou nos paths
      type: http
      scheme: bearer
      bearerFormat: JWT

